language: go
install:
  - go get -u github.com/elazarl/goproxy
  - go get -u github.com/inconshreveable/go-vhost
  - go get -u github.com/gorilla/context
  - go get -u github.com/gorilla/sessions
  - go get -u github.com/mzimmerman/ldap
script:
- go test -bench . -race
- go test -bench .
