language: go
install:
  - go get -u github.com/elazarl/goproxy
  - go get -u github.com/inconshreveable/go-vhost
  - go get -u github.com/HouzuoGuo/tiedot/db
script:
- go test -bench . -race
- go test -bench .
